const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'Nike-Slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      crand: 'Nike',
      raintg: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'Adidas-Fit-Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 20,
      crand: 'Adidas',
      raintg: 4.0,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'Nike-Slim-Pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      crand: 'Nike',
      raintg: 4.5,
      numReviews: 14,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'Adidas-Fit-Pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      crand: 'Adidas',
      raintg: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
  ],
};
export default data;
