import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Daimel',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'john',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      //      _id: '1',
      name: 'Nike Slim shirt',
      slug: 'Nike-Slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      crand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
      weight: 300,
    },
    {
      //    _id: '2',
      name: 'Adidas Fit Shirt',
      slug: 'Adidas-Fit-Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 0,
      crand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality shirt',
      weight: 400,
    },
    {
      //_id: '3',
      name: 'Nike Slim Pant',
      slug: 'Nike-Slim-Pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      crand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality shirt',
      weight: 650,
    },
    {
      //_id: '4',
      name: 'Adidas Fit Pant',
      slug: 'Adidas-Fit-Pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      crand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
      weight: 500,
    },
  ],
};
export default data;
